#!/bin/bash
# Uninstalls the andor sdk.

# These lines may need to be edited for a specific system #################
module_dir=/lib/modules/`uname -r`
rc_dir=/etc
rc_file=rc.local
hotplug_dir=/etc/hotplug
udev_dir=/etc/udev
###########################################################################


if [ `id -u` -ne 0 ]
then
  echo "You must have root priveleges to install the andor software."
  exit 1
fi

if [ ! -f /etc/andor/andor.install ]
then
  echo "No Installation log /etc/andor/andor.install... exiting"
  exit 0  
fi

#get installation directory
CNT=`awk 'BEGIN {DIRCOUNT=0} {if(NF>0) DIRCOUNT+=1} END {print DIRCOUNT}' /etc/andor/andor.install`

#CNT should now store a number from 0 upwards

if [ $CNT -ne 0 ]
then
  if [ $CNT -gt 1 ]
  then
    echo $CNT install Directories found...
  
    awk '{if(NF>0) {DIRCOUNT+=1; print DIRCOUNT".",$1}}' /etc/andor/andor.install
    echo "Select installation directory:"
    read index
  
    if [ $index -lt 1 ] || [ $index -gt $CNT ]
    then
      echo "Index Out of range, exiting..."
      exit 1;
    fi
  
  else
    index=1
  fi
  
  installdir=`awk -v awkindex=$index '{if(NF>0) {DIRCOUNT+=1} if(DIRCOUNT==awkindex) print $1}' /etc/andor/andor.install` 
  
else
  echo "No installations detected... exiting"
  exit 0
fi

if [ ! -d $installdir ]
then
  echo "Installation directory $installdir not found... exiting"
  #remove from install record
  echo $installdir | sed 's/\//\\\//g' > tmpfile.tmp
  installdirslash=`cat tmpfile.tmp`
  rm -f tmpfile.tmp
  sed '/'$installdirslash'/d' /etc/andor/andor.install > andor.install.tmp
  mv andor.install.tmp /etc/andor/andor.install
  exit 1
fi

#remove runtime configuration files
echo "Removing run-time configuration files from $installdir/etc..."
if [ -d $installdir/etc/andor ]
then
  rm -f $installdir/etc/andor/*
  rmdir $installdir/etc/andor
fi

#remove include files
echo "Removing include files from $installdir/include..."
if [ -d $installdir/include ]
then
  rm -f $installdir/include/atmcdLXd.h
  rm -f $installdir/include/ATSIFIO.h
  rm -f $installdir/include/ATSIFTypes.h
  rm -f $installdir/include/ATSIFErrorCodes.h
  rm -f $installdir/include/ATSIFProperties.h
  rm -f $installdir/include/ATPrimitiveTypes.h
  rm -f $installdir/include/ATLibraryExport.h
fi

#remove help files
echo "Removing help files from $installdir/doc..."
if [ -d $installdir/doc ]
then
  rm -f "$installdir/doc/Software Development Kit.pdf"
  rm -f "$installdir/doc/Andor SIF API.doc"
fi

#remove library files
echo "Removing library files from $installdir/lib..."
if [ -d $installdir/lib ]
then
  rm -f $installdir/lib/libatusbfs.* $installdir/lib/libandor.*
  rm -f $installdir/lib/libatusbfs.* $installdir/lib/libatsifio.*
  rm -f $installdir/lib/libshamrockcif.*
  rm -f $installdir/lib/libUSBI2C.*
fi

#update the system library cache
echo "Updating library cache, please wait..."
/sbin/ldconfig $installdir/lib

#remove hotplugging scripts
echo "Removing USB hotplug scripts..."
if [ -d $hotplug_dir/usb ]
then
  rm -f $hotplug_dir/usb/andor.usermap
  rm -f $hotplug_dir/usb/andor
fi

if [ -d $udev_dir/rules.d ]
then
  rm -f $udev_dir/rules.d/andor.rules
fi

#find out where the local boot script is located for removing automatic load of pci driver module
echo "Removing pci module and scripts..."
if [ ! -e $rc_dir/$rc_file ]
then
    rc_dir=/etc/init.d
    rc_file=boot.local
fi

if [ -e $rc_dir/$rc_file ]
then
  module_script="andordrvlx_load"
  more $rc_dir/$rc_file | sed '/Run Andor Technology/d' > temp.rc
  cat temp.rc > $rc_dir/$rc_file
  more $rc_dir/$rc_file | sed '/andordrvlx_load/d' > temp.rc
  cat temp.rc > $rc_dir/$rc_file

  rm -f $rc_dir/$module_script

  /sbin/rmmod andordrvlx 2>/dev/null
  rm -f $module_dir/andordrvlx*

  echo "Updating module dependencies, please wait..."
  /sbin/depmod -a
fi

#remove from install record
echo $installdir | sed 's/\//\\\//g' > tmpfile.tmp
installdirslash=`cat tmpfile.tmp`
rm -f tmpfile.tmp
sed '/'$installdirslash'/d' /etc/andor/andor.install > andor.install.tmp
mv andor.install.tmp /etc/andor/andor.install

CNT=`awk 'BEGIN {DIRCOUNT=0} {if(NF>0) DIRCOUNT+=1} END {print DIRCOUNT}' /etc/andor/andor.install`
if [ $CNT -eq 0 ]
then
  rm -f /etc/andor/andor.install
  rm -rf /etc/andor/*
  rmdir /etc/andor
fi

echo "Complete."
