#!/bin/sh
# Installs the andor driver.

DEV="andordrvlx"

/sbin/modprobe -qs $DEV $* || exit 1

# retrieve major number of module
major=`grep $DEV /proc/devices | awk "{print \\$1}"`

# make device nodes
cd /dev
rm -f andordrvlx0 andordrvlx1

mknod andordrvlx0 c $major 0
mknod andordrvlx1 c $major 1

chmod go+rw andordrvlx0 andordrvlx1

echo 'andor driver installed'
