#!/bin/sh
# Installs the andor driver.

FILE="andordrvlx.*o"
DEV="andordrvlx"

/sbin/insmod -f $FILE $* || (echo "$DEV not inserted" ; exit 1)

# retrieve major number of module
major=`grep $DEV /proc/devices | awk "{print \\$1}"`

# make device nodes
cd /dev
rm -f andordrvlx0 andordrvlx1

mknod andordrvlx0 c $major 0
mknod andordrvlx1 c $major 1

chmod go+rw andordrvlx0 andordrvlx1
